# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: thecodersbrain
email: JohnECossack@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A unique perspective on would-be coders as a simple blog evolves alongside the educational process of a newbie coder to his journey of becoming a promanent force in the Web Development Industry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://TheCodersBrain.com" # the base hostname & protocol for your site
twitter_username: johncossack
github_username:  greatmaddyave

# Build settings
markdown: kramdown
